package nl.timonschultz.baseapp.api.provider;

import nl.timonschultz.baseapp.api.model.BaseModel;
import org.springframework.stereotype.Service;

@Service
public class BaseProvider {

    public BaseModel provideBaseModel() {
        return new BaseModel("foo", "This is a model generated by the backend service");
    }

    public BaseModel provideBaseModel(String name, String message) {
        return new BaseModel(name, message + " - created");
    }

}